version: "3.7"

services:
  frontend:
    container_name: frontend_sysken_intro
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    ports:
      - 8080:8080
    command: npm run serve
    volumes:
      - ./frontend/:/app/
